# Generated by Django 4.2.7 on 2023-12-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_user', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowedBook',
        ),
    ]
