# Generated by Django 4.2.7 on 2023-12-29 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0004_rename_brand_bookmodel_category'),
        ('library_user', '0003_delete_borrowedbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.bookmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_user.useraccountmodel')),
            ],
        ),
    ]
