# Generated by Django 4.2.7 on 2023-12-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_user', '0004_borrowedbookmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowedBookModel',
        ),
    ]
