# Generated by Django 4.2.7 on 2023-12-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_user', '0007_alter_borrowedbookmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
