# Generated by Django 4.2.7 on 2023-12-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_user', '0008_remove_comment_email_remove_comment_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
