# Generated by Django 4.2.7 on 2023-12-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_user', '0010_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
